### ISSUE TITLE
Difference between operation_retry and connection_retry

### ISSUE THREAD

**Issue by sammoh94** [streamnative/pulsar-rs#152]
I am trying to understand when the operation_retry_options config will be used and when the connection_retry_options config will be used.

I have the following cases in mind:

- Client lost connection and is trying to reconnect to the pulsar broken which is running fine
- Client is trying to connect/ reconnect but the pulsar broker is down
- Client is connected and ingesting data and then the pulsar broker goes down

Is it correct to assume that in the first and second case, the connection_retry_options configuration will be used but in the second, the operations_retry_options config will be used? Moreover, is it correct to assume that the operation_retry_config will be used for any operation that fails for the client (producer/ consumer) due to a broker outage?

Also if anyone could point me to some documentation about this, that would be very helpful

Thanks!

**Comment by Geal** [comment]
the connection retry options are linked to the actual network connection to a broker or proxy, which can fail, while the operations are linked to the actual messages going over those connections, and the operations they are linked to, like subscribing or sending a message on a topic. They have very different failure modes.

Connection retries ( https://docs.rs/pulsar/2.0.0/pulsar/struct.ConnectionRetryOptions.html ) are linked to network failures, so they are typically handled by an exponential backoff  (wincreasing the time between retries on each connection failure), and after a while, should just give up and let the application decide what to do (send an alert to monitoring systems, reboot the machine, etc), because the pulsar client will not be able to fix it. A connection retry is triggered when a message send returned a network error (we send pings regularly to test the connection).

Note that a single connection can be used by multiple producers and consumers, so when we detect that a connection is down, the connection retries can be mutualized (there will be a new lookup though, so they could end up reconnecting to other brokers).

Operation retries ( https://docs.rs/pulsar/2.0.0/pulsar/struct.OperationRetryOptions.html ) assume we have a proper connection to the broker, but there might be another logic issue, like when the topic is moved to another broker, or some brokers are restarting and we must wait for them to answer. In those cases, we could get `ServiceNotReady` errors, upon which the client must lookup again the topic and retry the operations. Sometimes we have to wait for a while for the cluster to be ready to answer again, but we assume that it will eventually resolve the issues, so the retry is not done with exponential backoff, and we can configure it to retry indefinitely.

**Comment by sheldonkwok** [comment]
Where is the code to send pings in the consumer? I saw there is a `check_connections` [function](https://github.com/wyyerd/pulsar-rs/blob/master/src/consumer.rs#L108) that will send pings out but I don't see it called anywhere. I saw the connection returns pongs. The Pulsar protocol said it was okay for the consumers to not send out the pings so I was wondering if that's how this client worked. http://pulsar.apache.org/docs/en/develop-binary-protocol/#keep-alive

Thanks!
