### ISSUE TITLE
Improve / abstract serialization and deserialization

### ISSUE THREAD

**Issue by stearnsc** [streamnative/pulsar-rs#24]
Currently the `serde` and `serde_json` crates are dependencies, but it would be nice for them to be optional (feature-gated), and provide a better / more unified experience for people using other solutions. 

In the spirit of making getting started as easy as possible, I think a good outcome would be for people who use serde to be able to send/receive types that impl Serialize + Deserialize without having to do any manual setup (or at least as minimal as possible), and for people doing something else to be able to "drop in" a replacement with a small amount of configuration (impl'ing a trait or two seems reasonable).

**Comment by Geal** [comment]
there might be a simple way to do that: remove serialization and deserialization from the producer and consumer API, and instead provide a nice API around the messages. Instead of having `send`, `send_json`, `send_raw`, let's just have `send_message`, but provide code examples for serialization.
On the consumer side, let's have a `Stream` of messages that will be parsed directly by the client code.

It will make simplify integration with other formats like Avro or Protobuf, and using the schema registry. It will also make message batching much easier to implement.
what do you think?

**Comment by stearnsc** [comment]
We have the `SerializeMessage` and `DeserializeMessage` traits; how would you feel about having `send_message` be generic over `T: SerializeMessage` or similar? (and same for the `Stream` impl on the consumer). Or are there things that just working with `&[u8]` and `Vec<u8>` buys us from an implementation perspective that I'm missing?

**Comment by stearnsc** [comment]
I went through and pulled the serde dependencies in favor of the above traits, and also made some other minor restructures (`send_raw` taking a `Message` instead of bytes, etc). It's on https://github.com/wyyerd/pulsar-rs/pull/45 if you want to take a look before I merge it in (and obviously I haven't published it yet, so time to change stuff if you foresee issues).

**Comment by Geal** [comment]
I'll look at it later today, thanks

**Comment by Geal** [comment]
from what I see, it can be useful to have some state management in the serialize/deserialize part (counting, message indexes, chunking, etc). Which is hard with the traits as they are. And if we need to get a schema dynamically (which is a thing apache people like to do) depending on the message, it will be hard to do from inside the trait.

**Comment by Geal** [comment]
that should be fine for now, you're right

**Comment by Geal** [comment]
cf #92
