### ISSUE TITLE
Creating a Producer from a dedicated function always result in a 'Disconnected' state

### ISSUE THREAD

**Issue by PierreZ** [streamnative/pulsar-rs#35]
Hi!

I'm having trouble creating a Producer from a dedicated function. I'm always experiencing a disconnect when returning a Producer. Here's a example that is reproducing the bug:

```rust
    pub fn new_basic_producer() -> Result<Producer, ConnectionError> {
        let runtime = tokio::runtime::Runtime::new().unwrap();
        Producer::new(String::from("127.0.0.1:6650"), "topic", None, None, None, runtime.executor()).wait()
    }

    #[test]
    fn cloneable() {
        let producer = new_basic_producer().unwrap();
        let serialized = vec![240, 159, 146, 150];
        let send_1 = producer.send_raw(serialized, None).wait().unwrap();
    }
```

> thread 'tests::cloneable' panicked at 'called `Result::unwrap()` on an `Err` value: Disconnected', src/libcore/result.rs:999:5

If I put back the Producer inline, everything is working. Same issue when creating a Pool using r2d2::Pool.

**Comment by stearnsc** [comment]
Thanks for reaching out!

Your issues is that the tokio runtime will shut down as soon as it goes out of scope (in this case at the end of your `new_basic_producer` function), which means any client depending on that runtime will stop working. The typical approach for an application is to create a single tokio runtime in main, use it to create any dependencies, and let it exit scope at the end of main. In your specific case, you have a couple options:

If you change it to 
```rust
   pub fn new_basic_producer(executor: TaskExecutor) -> Result<Producer, ConnectionError> {
        Producer::new(String::from("127.0.0.1:6650"), "topic", None, None, None, executor).wait()
    }

    #[test]
    fn cloneable() {
        let runtime = tokio::runtime::Runtime::new().unwrap();
        let producer = new_basic_producer(runtime.executor()).unwrap();
        let serialized = vec![240, 159, 146, 150];
        let send_1 = producer.send_raw(serialized, None).wait().unwrap();
    }
```
it should work. However, I'd probably instead do something like:
```rust
use tokio::prelude::*;
use tokio::runtime::Runtime;
use lazy_static::lazy_static;
use pulsar::Pulsar;

lazy_static! {
    static ref RUNTIME: Runtime = Runtime::new().unwrap();
    static ref PULSAR: Pulsar = Pulsar::new("127.0.0.1:6650".parse().unwrap(), None, RUNTIME.executor()).wait().unwrap();
}

#[test]
fn cloneable() {
    let mut producer = PULSAR.create_producer("oops this isn't used anymore :(", None).wait();
    let serialized = vec![240, 159, 146, 150];
    let send_1 = producer.send_raw("topic", serialized, None).wait().unwrap();
}
```
although you'd need to update to pulsar 0.1.4 to use the `Pulsar` client that way. We're moving the API for producers and consumers to be much more reliant on the `Pulsar` client, so I'd recommend using that instead of creating the producer manually, which probably won't be an option in future releases. The client will also handle connection sharing and multiplexing, so should cover all of the uses the r2d2 adapter currently does.

If you do choose to use the `Pulsar` client without r2d2, and run into any issues with your use case that r2d2 would have solved, please let me know :). Also, if you want to produce to multiple topics conveniently, you can depend on the master branch as it has some more modern functionality (basically an engine to lazily create producers as needed for writing to multiple topics, efficiently re-using connections to do so). If you need that functionality but don't want to depend on master, let me know and I'll release another version w/ that stuff.

**Comment by PierreZ** [comment]
Thank you for your reply!

Good catch for the Tokio Runtime 😆 I thought that it would have been catch by the compiler, but I guess not. 

I will play with the pulsar::Pulsar on master, and see if I can found some issues. If not, you could make a release with an updated README. Do you need some help regarding this?

**Comment by stearnsc** [comment]
If you have the time to update the README, that would be super helpful. As soon as async/await lands on stable I'll be updating the whole lib to use std::futures instead of futures 0.1, so was planning to do the README update + next release then, but if you update the README before then, I definitely can throw up a new version.

**Comment by PierreZ** [comment]
Ok, I will update the README then! 

Cool to know that async/await is coming, I'm currently using [Runtime](https://github.com/rustasync/runtime) and [Future01CompatExt](https://rust-lang-nursery.github.io/futures-api-docs/0.3.0-alpha.14/futures/compat/trait.Future01CompatExt.html) for now, it works perfectly!

```rust
use futures::compat::Future01CompatExt;
use pulsar::Pulsar;
use tokio::runtime::Runtime;
// ...
let response = match self.cnx.send_raw(topic_name, record.value, None)
                                .compat().await {
// ...
```
