### ISSUE TITLE
Expose Pulsar healthcheck

### ISSUE THREAD

**Issue by KannarFr** [streamnative/pulsar-rs#76]
https://github.com/timberio/vector/issues/2475#issuecomment-620584645

**Comment by Geal** [comment]
so this should work with f43186c, but there will not be a global healthcheck method: the server we connect to with the client might not be the one we connect to when creating a producer or consumer, so right now, the `check_connection()` method is available on the producer and consumer objects.
It's probably not good enough in the general case though, because multiple producers and consumers could be using the same TCP connection, but ping messages are global on a connection.
So a better solution might be to expose a stream of "pong" for a connection, and the producers and consumers on it could share that stream (and any of them could ping as needed)

**Comment by KannarFr** [comment]
For the usage of vector I think it's enough yet. Can you do a release of with it?

**Comment by Geal** [comment]
done in 1.0 release
